// The roster.
//
// Five to start, one per role, each drawn from a real figure in Philippine
// folklore rather than a reskin of a western archetype. The lore lines are not
// decoration: they are the only place the myth is told, and a player who never
// reads them should still learn what a Tikbalang is from how it plays.
//
// ⚠ IDS ARE PERMANENT NAMES. A save, a match record and a ladder entry all
// refer to a hero by id. Rename the `name`, never the `id`.
//
// BALANCE NOTES live beside the numbers they explain, because a number with no
// reason attached is a number nobody dares to change.
//
// ⚠ PALETTES ARE SATURATED AND BRIGHT, and that is a readability requirement
// rather than a taste. The first set was muted and earthy, which looked right
// in isolation and made every hero vanish into the foliage. In a game built on
// aimed abilities, a player has to find five bodies instantly; a hero who
// blends into the ground is a hero nobody can fight or fight against.

import type { Hero } from './types';

export const HEROES: Hero[] = [
  {
    id: 'tikbalang',
    name: 'Tikbalang',
    title: 'Ang Tagapagligaw ng Kagubatan',
    baybayin: 'ᜆᜒᜃ᜔ᜊᜎᜅ᜔',
    quote: 'Ibaligtad mo ang iyong damit, bago ka tuluyang mawala sa gubat.',
    passive: {
      id: 'tikbalang-passive',
      name: 'Baliktad na Damit',
      blurb: 'Moving through jungle brush grants 25% movement speed and generates a 120 HP earthen shield.',
      emoji: '🌿',
      effect: '+25% Brush SPD & +120 HP Shield',
    },
    model: {
      rigged: '/models/heroes/tikbalang-rigged.glb',
      walk: '/models/heroes/tikbalang-walk.glb',
    },
    origin: 'The horse-headed trickster of the forest trails',
    lore:
      'It turns travellers in circles until they give up on the path they chose. Wear your shirt inside out and it lets you pass, which is the only apology it knows how to make.',
    role: 'vanguard',
    emoji: '🐴',
    palette: { skin: '#8a5a3c', cloth: '#2f6f57', accent: '#ffd24a', hair: '#241a14' },
    // The tankiest and the slowest to act. A vanguard that is also quick has no
    // weakness, and every fight becomes about who has one.
    // The tallest and heaviest thing on the field, carrying nothing: a
    // vanguard's threat is its own body.
    build: { scale: 1.22, bulk: 1.25, gear: [] },
    health: 1150,
    speed: 6.2,
    attack: 62,
    attackRange: 2.2,
    attackCooldown: 0.85,
    abilities: [
      {
        id: 'tikbalang-charge',
        name: 'Trailbreak',
        blurb: 'Charges forward and throws whoever it meets back over its shoulder.',
        emoji: '💨',
        shape: 'dash',
        cooldown: 9,
        range: 7,
        width: 1.1,
        damage: 110,
        // Long wind-up for a long dash. This is the initiation of a whole fight,
        // so the other team is owed a moment to see it coming.
        windup: 0.35,
        lock: 0,
      },
      {
        id: 'tikbalang-maze',
        name: 'Turned Around',
        blurb: 'A ring of false trails. Anyone inside it loses sight of everything outside.',
        emoji: '🌫',
        shape: 'ground',
        cooldown: 14,
        range: 8,
        width: 3.4,
        damage: 40,
        windup: 0.6,
        lock: 0.25,
      },
      {
        id: 'tikbalang-stomp',
        name: 'Hoof Stomp',
        blurb: 'Slams hooves down, sending a shockwave in front of the caster.',
        emoji: '💥',
        shape: 'cone',
        cooldown: 7,
        range: 4.5,
        width: 0.9,
        damage: 100,
        windup: 0.25,
        lock: 0.1,
      },
    ],
    ultimate: {
      id: 'tikbalang-stampede',
      name: 'Stampede',
      blurb: 'The forest runs with it. A wide charge that carries every enemy it touches.',
      emoji: '🌪',
      shape: 'dash',
      cooldown: 70,
      range: 14,
      width: 2.4,
      damage: 260,
      windup: 0.5,
      lock: 0,
    },
  },
  {
    id: 'mangkukulam',
    name: 'Mangkukulam',
    title: 'Ang Mananambal at Manggagaway',
    baybayin: 'ᜋᜅ᜔ᜃᜓᜃᜓᜎᜋ᜔',
    quote: 'Isang hibla ng buhok mo lamang, hawak ko na ang iyong kapalaran.',
    passive: {
      id: 'kulam-passive',
      name: 'Buhok at Karayom',
      blurb: 'Abilities apply a Hex stack. At 3 stacks, detonates for 140 bonus magic damage and slows target.',
      emoji: '🪡',
      effect: '3-Stack Hex Detonation (+140 Dmg)',
    },
    origin: 'The one who works harm at a distance',
    lore:
      'Never seen at the act. A doll, a strand of hair, a name said the wrong number of times, and a person three towns away sits down and does not get up.',
    role: 'mystic',
    emoji: '🪡',
    palette: { skin: '#b07f57', cloth: '#7a3fa8', accent: '#ff5f8f', hair: '#1a1418' },
    build: { scale: 0.94, bulk: 0.92, gear: ['cape', 'pouch'] },
    model: {
      rigged: '/models/heroes/diwata-rigged.glb',
      walk: '/models/heroes/diwata-walk.glb',
    },
    health: 720,
    speed: 6.0,
    attack: 48,
    attackRange: 7.5,
    attackCooldown: 1.0,
    abilities: [
      {
        id: 'kulam-pin',
        name: 'The Pin',
        blurb: 'Marks a spot. Whoever stands there when it lands carries the hurt with them.',
        emoji: '📍',
        shape: 'ground',
        cooldown: 7,
        range: 9,
        width: 1.8,
        damage: 130,
        windup: 0.85,
        lock: 0.3,
      },
      {
        id: 'kulam-thread',
        name: 'Red Thread',
        blurb: 'A line drawn between two people. What one of them suffers, so does the other.',
        emoji: '🧵',
        shape: 'projectile',
        cooldown: 12,
        range: 11,
        width: 0.5,
        damage: 70,
        windup: 0.25,
        lock: 0.2,
      },
      {
        id: 'kulam-hex',
        name: 'Hex Curse',
        blurb: 'Blows a cone of cursed ash that dazes and weakens everything it touches.',
        emoji: '🧿',
        shape: 'cone',
        cooldown: 8,
        range: 6.5,
        width: 0.8,
        damage: 95,
        windup: 0.3,
        lock: 0.2,
      },
    ],
    ultimate: {
      id: 'kulam-effigy',
      name: 'Effigy',
      blurb: 'Everything done to the doll for the next few seconds is done to them.',
      emoji: '🕯',
      shape: 'ground',
      cooldown: 90,
      range: 10,
      width: 4.2,
      damage: 300,
      windup: 1.1,
      lock: 0.6,
    },
  },
  {
    id: 'aswang',
    name: 'Aswang',
    title: 'Ang Maninila ng Kadiliman',
    baybayin: 'ᜀᜐ᜔ᜏᜅ᜔',
    quote: 'Huwag kang titingin sa tubig, baka makita mo ang iyong sariling wakas.',
    passive: {
      id: 'aswang-passive',
      name: 'Amoy ng Dugo',
      blurb: 'Gains 30% bonus attack speed against targets below 40% HP and 15% physical lifesteal.',
      emoji: '🩸',
      effect: '+30% Low-HP ATK Speed & 15% Lifesteal',
    },
    model: {
      rigged: '/models/heroes/aswang-rigged.glb',
      walk: '/models/heroes/aswang-walk.glb',
    },
    origin: 'The shape that is not the shape you saw',
    lore:
      'By day it is a neighbour who asks after your mother. The tell is the reflection: look at its eyes in water and you are standing upside down in them.',
    role: 'stalker',
    emoji: '🦇',
    palette: { skin: '#9a6a4f', cloth: '#3a2f4a', accent: '#e03a4a', hair: '#0f0d10' },
    build: { scale: 0.98, bulk: 0.82, gear: ['knives'] },
    health: 780,
    speed: 7.6,
    attack: 74,
    attackRange: 2.0,
    attackCooldown: 0.65,
    abilities: [
      {
        id: 'aswang-shift',
        name: 'Change',
        blurb: 'Drops to four legs and runs. Faster, quieter, and it cannot strike while it runs.',
        emoji: '🐕‍🦺',
        shape: 'dash',
        cooldown: 8,
        range: 9,
        width: 0.9,
        damage: 0,
        windup: 0.15,
        lock: 0,
      },
      {
        id: 'aswang-rend',
        name: 'From Behind',
        blurb: 'A short lunge that cuts far deeper when it lands on a back.',
        emoji: '🩸',
        shape: 'cone',
        cooldown: 6,
        range: 3.2,
        width: 0.6,
        damage: 150,
        windup: 0.2,
        lock: 0.15,
      },
      {
        id: 'aswang-slash',
        name: 'Blood Arc',
        blurb: 'Sweeps razor talons in a wide crimson arc that slices nearby foes.',
        emoji: '🗡',
        shape: 'cone',
        cooldown: 6,
        range: 4.0,
        width: 0.7,
        damage: 125,
        windup: 0.2,
        lock: 0.15,
      },
    ],
    ultimate: {
      id: 'aswang-unmake',
      name: 'Unmake',
      blurb: 'Sheds the borrowed shape entirely. Everything nearby learns what was under it.',
      emoji: '🌑',
      shape: 'cone',
      cooldown: 75,
      range: 5.5,
      width: 1.1,
      damage: 340,
      windup: 0.45,
      lock: 0.4,
    },
  },
  {
    id: 'diwata',
    name: 'Diwata',
    title: 'Ang Tagapag-ingat ng Kagubatan',
    baybayin: 'ᜇᜒᜏᜆ',
    quote: 'Magbigay-galang sa lupa, bago kayo lamunin ng mga ugat.',
    passive: {
      id: 'diwata-passive',
      name: 'Tabi-tabi Po',
      blurb: 'Standing near allied structures or shrines heals 18 HP/sec and grants 10% cooldown haste.',
      emoji: '🌿',
      effect: '+18 HP/s Structure Aura & 10% Haste',
    },
    model: {
      rigged: '/models/heroes/diwata-rigged.glb',
      walk: '/models/heroes/diwata-walk.glb',
    },
    origin: 'The keeper of a place that was there first',
    lore:
      'Ask before you cut the tree. Say tabi-tabi po before you cross the mound. She is not unkind, she is simply owed a courtesy nobody remembers to pay.',
    role: 'warden',
    emoji: '🌿',
    palette: { skin: '#e0b98a', cloth: '#2fae7a', accent: '#ffe98a', hair: '#4a3220' },
    build: { scale: 1.04, bulk: 0.95, gear: ['cape'] },
    health: 860,
    speed: 6.4,
    attack: 44,
    attackRange: 6.5,
    attackCooldown: 1.05,
    abilities: [
      {
        id: 'diwata-ward',
        name: 'Tabi-tabi',
        blurb: 'Ground nobody may cross without asking. It slows those who try anyway.',
        emoji: '🛡',
        shape: 'ground',
        cooldown: 11,
        range: 7,
        width: 3.0,
        damage: 0,
        windup: 0.4,
        lock: 0.2,
      },
      {
        id: 'diwata-santelmo',
        name: 'Santelmo',
        blurb: 'A ball of cold fire that mends whoever it passes through on the way.',
        emoji: '🔵',
        shape: 'projectile',
        cooldown: 8,
        range: 10,
        width: 0.7,
        damage: 85,
        windup: 0.2,
        lock: 0,
      },
      {
        id: 'diwata-gust',
        name: 'Amihan Breeze',
        blurb: 'Calls a gust of mountain wind that pushes foes and invigorates allies.',
        emoji: '🍃',
        shape: 'cone',
        cooldown: 9,
        range: 6.0,
        width: 0.9,
        damage: 70,
        windup: 0.25,
        lock: 0.1,
      },
    ],
    ultimate: {
      id: 'diwata-grove',
      name: 'The Grove Answers',
      blurb: 'The place itself takes a side. Roots hold, and the wounded stop bleeding.',
      emoji: '🌳',
      shape: 'ground',
      cooldown: 85,
      range: 8,
      width: 5.0,
      damage: 120,
      windup: 0.9,
      lock: 0.5,
    },
  },
  {
    id: 'bernardo',
    name: 'Bernardo Carpio',
    title: 'Ang Higante ng Montalban',
    baybayin: 'ᜊᜒᜇ᜔ᜈᜇ᜔ᜇᜓ',
    quote: 'Kapag akoy kumilos, yayanig ang buong kapuluan!',
    passive: {
      id: 'bernardo-passive',
      name: 'Gipit na Bundok',
      blurb: 'Takes 15% reduced damage from physical strikes; basic attacks cleave in a 1.5u seismic arc.',
      emoji: '⛰',
      effect: '+15% Physical Armor & Seismic Cleave',
    },
    model: {
      rigged: '/models/heroes/tikbalang-rigged.glb',
      walk: '/models/heroes/tikbalang-walk.glb',
    },
    origin: 'The strength held between two mountains',
    lore:
      'He stands in the gap in the Montalban range with a hand on each cliff. When he shifts his shoulders, the ground in Manila moves. He has been getting free for a very long time.',
    role: 'ranger',
    emoji: '⛰',
    palette: { skin: '#c08a58', cloth: '#c96a2f', accent: '#cfd8de', hair: '#20160f' },
    build: { scale: 1.14, bulk: 1.18, gear: ['crossbow'] },
    health: 820,
    speed: 6.1,
    attack: 66,
    attackRange: 8.5,
    attackCooldown: 1.15,
    abilities: [
      {
        id: 'bernardo-slab',
        name: 'Slab',
        blurb: 'Tears a piece of the hillside loose and throws it flat along the ground.',
        emoji: '🪨',
        shape: 'projectile',
        cooldown: 7,
        range: 12,
        width: 0.9,
        damage: 140,
        windup: 0.35,
        lock: 0.25,
      },
      {
        id: 'bernardo-wall',
        name: 'The Gap',
        blurb: 'Stands a wall of rock where there was a path. It will not last, but it will hold.',
        emoji: '🧱',
        shape: 'ground',
        cooldown: 16,
        range: 8,
        width: 3.6,
        damage: 0,
        windup: 0.5,
        lock: 0.3,
      },
      {
        id: 'bernardo-cleave',
        name: 'Fault Line',
        blurb: 'Slams a seismic fissure through the ground in front of him.',
        emoji: '⚡',
        shape: 'cone',
        cooldown: 8,
        range: 5.5,
        width: 0.8,
        damage: 150,
        windup: 0.3,
        lock: 0.2,
      },
    ],
    ultimate: {
      id: 'bernardo-quake',
      name: 'Shoulders',
      blurb: 'He shifts his weight, and everything standing on the ground stops standing.',
      emoji: '🌋',
      shape: 'ground',
      cooldown: 80,
      range: 11,
      width: 6.0,
      damage: 280,
      windup: 1.0,
      lock: 0.7,
    },
  },
  {
    id: 'manananggal',
    name: 'Manananggal',
    title: 'Ang Maninila sa Hatinggabi',
    baybayin: 'ᜋᜈᜈᜅ᜔ᜄᜎ᜔',
    quote: 'Sa pagpatak ng dilim, maririnig mo ang pagaspas ng aking pakpak.',
    passive: {
      id: 'manananggal-passive',
      name: 'Hating-Katawan',
      blurb: 'Glides across river water and jungle chokepoints with zero terrain friction and +12% lifesteal.',
      emoji: '🦇',
      effect: 'Water Glide Terrain Ignore & 12% Vamp',
    },
    model: {
      rigged: '/models/heroes/aswang-rigged.glb',
      walk: '/models/heroes/aswang-walk.glb',
    },
    origin: 'The night predator that severs its body in two',
    lore:
      'By dusk she rubs enchanted oil on her skin and splits at the waist. Her bat-winged torso hunts the night skies while her lower half stands hidden beneath banana groves.',
    role: 'stalker',
    emoji: '🩸',
    palette: { skin: '#8b5a5a', cloth: '#3d1c24', accent: '#ff1744', hair: '#110b10' },
    build: { scale: 1.02, bulk: 0.85, gear: ['knives'] },
    health: 760,
    speed: 7.8,
    attack: 78,
    attackRange: 2.1,
    attackCooldown: 0.62,
    abilities: [
      {
        id: 'manananggal-flight',
        name: 'Night Wings',
        blurb: 'A swift aerial dash that cuts through enemies and leaves a trail of venom.',
        emoji: '🦇',
        shape: 'dash',
        cooldown: 7,
        range: 9.5,
        width: 1.0,
        damage: 135,
        windup: 0.18,
        lock: 0,
      },
      {
        id: 'manananggal-lash',
        name: 'Viscera Lash',
        blurb: 'Fires an elongated barbed tongue that strikes with agonizing force.',
        emoji: '👅',
        shape: 'projectile',
        cooldown: 10,
        range: 10,
        width: 0.6,
        damage: 160,
        windup: 0.22,
        lock: 0.15,
      },
      {
        id: 'manananggal-mist',
        name: 'Blood Mist',
        blurb: 'Releases a noxious cloud of cursed blood mist on target ground.',
        emoji: '🩸',
        shape: 'ground',
        cooldown: 8,
        range: 7.0,
        width: 2.8,
        damage: 90,
        windup: 0.25,
        lock: 0.15,
      },
    ],
    ultimate: {
      id: 'manananggal-screech',
      name: 'Midnight Sever',
      blurb: 'Unleashes a blood-curdling ultrasonic screech that tears through enemies in a wide cone.',
      emoji: '🌑',
      shape: 'cone',
      cooldown: 70,
      range: 6.5,
      width: 1.2,
      damage: 360,
      windup: 0.4,
      lock: 0.35,
    },
  },
  {
    id: 'mayari',
    name: 'Mayari',
    title: 'Ang Diyosa ng Buwan at Digmaan',
    baybayin: 'ᜋᜌᜇᜒ',
    quote: 'Bagamat iisa ang aking mata, malinaw kong nakikita ang inyong kahihinatnan.',
    passive: {
      id: 'mayari-passive',
      name: 'Sinag ng Bulan',
      blurb: 'Landing skillshots at max range restores 45 HP and slows target movement by 20% for 1.5s.',
      emoji: '🌙',
      effect: 'Max-Range Spell +45 HP Heal & 20% Slow',
    },
    model: {
      rigged: '/models/heroes/diwata-rigged.glb',
      walk: '/models/heroes/diwata-walk.glb',
    },
    origin: 'The one-eyed Goddess of the Moon and War',
    lore:
      'Daughter of Bathala who rules the celestial night with serene silver brilliance. Though she lost an eye to Apolaki in their war for the sky, her lunar radiance guides the lost.',
    role: 'warden',
    emoji: '🌙',
    palette: { skin: '#f0d5b8', cloth: '#1a365d', accent: '#00e5ff', hair: '#2b2d42' },
    build: { scale: 1.06, bulk: 0.96, gear: ['cape'] },
    health: 890,
    speed: 6.5,
    attack: 52,
    attackRange: 6.8,
    attackCooldown: 0.95,
    abilities: [
      {
        id: 'mayari-shield',
        name: 'Bulan Aegis',
        blurb: 'Conjures a protective radiant moon crescent barrier that harms and slows intruders.',
        emoji: '🛡',
        shape: 'ground',
        cooldown: 9,
        range: 7.5,
        width: 3.2,
        damage: 60,
        windup: 0.35,
        lock: 0.15,
      },
      {
        id: 'mayari-beam',
        name: 'Lunar Ray',
        blurb: 'Fires a high-velocity beam of concentrated moonlight that pierces all targets.',
        emoji: '✨',
        shape: 'projectile',
        cooldown: 7.5,
        range: 11.5,
        width: 0.65,
        damage: 125,
        windup: 0.25,
        lock: 0.1,
      },
      {
        id: 'mayari-sweep',
        name: 'Crescent Sweep',
        blurb: 'Sweeps an arc of silver moonlight that cuts through nearby adversaries.',
        emoji: '🌙',
        shape: 'cone',
        cooldown: 7,
        range: 5.2,
        width: 0.85,
        damage: 110,
        windup: 0.22,
        lock: 0.1,
      },
    ],
    ultimate: {
      id: 'mayari-eclipse',
      name: 'Eclipse Burst',
      blurb: 'Calls down a blinding lunar eclipse pillar on target area, devastating enemy forces.',
      emoji: '🌕',
      shape: 'ground',
      cooldown: 80,
      range: 9.0,
      width: 5.2,
      damage: 290,
      windup: 0.85,
      lock: 0.5,
    },
  },
  {
    id: 'apolaki',
    name: 'Apolaki',
    title: 'Ang Soberanong Diyos ng Araw at Digmaan',
    baybayin: 'ᜀᜉᜓᜎᜃᜒ',
    quote: 'Sa ngalan ng Araw, walang aninong makapagtatago sa aking sibat!',
    passive: {
      id: 'apolaki-passive',
      name: 'Haring Araw',
      blurb: 'Attacks and spells ignite foes for 15 solar burn damage/sec and illuminate brush hiding spots.',
      emoji: '☀️',
      effect: '+15 Burn Dmg/s & True Sight in Brush',
    },
    model: {
      rigged: '/models/heroes/tikbalang-rigged.glb',
      walk: '/models/heroes/tikbalang-walk.glb',
    },
    origin: 'The Sovereign God of Sun and War',
    lore:
      'Patron lord of ancient warriors who commands the searing light of the noonday sun. With his golden Kalasag shield and flaming spear, he leads every charge.',
    role: 'vanguard',
    emoji: '☀️',
    palette: { skin: '#b87333', cloth: '#c0392b', accent: '#ffb300', hair: '#1a1a1a' },
    build: { scale: 1.2, bulk: 1.22, gear: ['cape'] },
    health: 1100,
    speed: 6.4,
    attack: 68,
    attackRange: 2.3,
    attackCooldown: 0.82,
    abilities: [
      {
        id: 'apolaki-charge',
        name: 'Kalasag Slam',
        blurb: 'Charges forward behind a blazing brass shield, knocking aside all obstacles.',
        emoji: '🛡',
        shape: 'dash',
        cooldown: 8,
        range: 8.0,
        width: 1.2,
        damage: 140,
        windup: 0.28,
        lock: 0,
      },
      {
        id: 'apolaki-spear',
        name: 'Sunburst Spear',
        blurb: 'Hurls a searing spear of solar fire that strikes with explosive force.',
        emoji: '🔱',
        shape: 'projectile',
        cooldown: 9,
        range: 11,
        width: 0.8,
        damage: 155,
        windup: 0.3,
        lock: 0.2,
      },
      {
        id: 'apolaki-flare',
        name: 'Solar Flare',
        blurb: 'Unleashes a blinding arc of solar rays that sears enemies in front of him.',
        emoji: '✨',
        shape: 'cone',
        cooldown: 7.5,
        range: 5.5,
        width: 0.85,
        damage: 135,
        windup: 0.24,
        lock: 0.15,
      },
    ],
    ultimate: {
      id: 'apolaki-wrath',
      name: 'Solar Wrath',
      blurb: 'Channels the blinding heat of high noon, creating a massive radial shockwave of golden flame.',
      emoji: '💥',
      shape: 'ground',
      cooldown: 75,
      range: 8.5,
      width: 5.5,
      damage: 320,
      windup: 0.8,
      lock: 0.55,
    },
  },
  {
    id: 'bakunawa',
    name: 'Bakunawa',
    title: 'Ang Higanteng Dragon ng Kalawakan',
    baybayin: 'ᜊᜃᜓᜈᜏ',
    quote: 'Ako ang lalamon sa liwanag, hanggang sa maghari ang walang hanggang dilim!',
    passive: {
      id: 'bakunawa-passive',
      name: 'Lamon ng Pitong Buwan',
      blurb: 'Slaying minions and creeps grants +2 ATK and +20 Max HP (stacks up to 20 times).',
      emoji: '🐉',
      effect: 'Stacking Moon Devour (+ATK & +HP on Kills)',
    },
    model: {
      rigged: '/models/creatures/kapre-rigged.glb',
      walk: '/models/creatures/kapre-walk.glb',
    },
    origin: 'The colossal serpent that swallows the moon',
    lore:
      'A primordial leviathan of the deep seas whose hunger pulls the tides and devours the celestial bodies. When it rises, the sky turns blood red.',
    role: 'mystic',
    emoji: '🐉',
    palette: { skin: '#1a365d', cloth: '#0f172a', accent: '#7c3aed', hair: '#020617' },
    build: { scale: 1.28, bulk: 1.35, gear: [] },
    health: 1050,
    speed: 5.9,
    attack: 60,
    attackRange: 6.2,
    attackCooldown: 1.1,
    abilities: [
      {
        id: 'bakunawa-wave',
        name: 'Tidal Surge',
        blurb: 'Unleashes a sweeping wave of abyssal sea water in front of the caster.',
        emoji: '🌊',
        shape: 'cone',
        cooldown: 8,
        range: 7.5,
        width: 0.9,
        damage: 145,
        windup: 0.35,
        lock: 0.2,
      },
      {
        id: 'bakunawa-vortex',
        name: 'Abyssal Maw',
        blurb: 'Summons a swirling whirlpool on target ground that crushes everything inside.',
        emoji: '🌀',
        shape: 'ground',
        cooldown: 13,
        range: 8.5,
        width: 3.8,
        damage: 110,
        windup: 0.6,
        lock: 0.3,
      },
      {
        id: 'bakunawa-coil',
        name: 'Leviathan Dash',
        blurb: 'Surges forward through tidal currents, crashing into enemies.',
        emoji: '🌊',
        shape: 'dash',
        cooldown: 8,
        range: 8.0,
        width: 1.1,
        damage: 120,
        windup: 0.25,
        lock: 0,
      },
    ],
    ultimate: {
      id: 'bakunawa-eclipse',
      name: 'Moon Devourer',
      blurb: 'Unleashes the ravenous cosmic maw of the serpent, sweeping across the field in a massive cone.',
      emoji: '🌌',
      shape: 'cone',
      cooldown: 85,
      range: 10.5,
      width: 1.4,
      damage: 350,
      windup: 0.95,
      lock: 0.65,
    },
  },
];

export const heroById = (id: string): Hero | undefined => HEROES.find((h) => h.id === id);
